name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - never-run-test
      - never-run
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@branch-24.10
    if: always()
  never-run-test:
    runs-on: ubuntu-latest
    outputs:
      run-never-run: false
    steps:
      - run: exit 0
  never-run:
    needs: never-run-test
    runs-on: ubuntu-latest
    if: ${{ needs.never-run-test.outputs.run-never-run == 'true' }}
    steps:
      - run: |
          echo "This should never run!"
          exit 1
